### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by tsuyoshicho** [tsuyoshicho/vim-efm-langserver-settings#1]
- [ ] 各Pluginのafterでのセットアップ処理追加 see lightline-ale
- [ ] efm-langserver設定格納
- [ ] 各設定ファイルどうするか?

**Comment by tsuyoshicho** [comment]
afterというより各プラグイン名以下にいれる

**Comment by tsuyoshicho** [comment]
設定ファイルを相対パスで設定するのがむずかしい... / フルパスをyamlに入れるわけにもいかないし...

**Comment by tsuyoshicho** [comment]
設定が必要で、かつホームの設定しか見れない系が入ると大変なことになる

**Comment by tsuyoshicho** [comment]
- [ ] 各機能(lsp/ale/coc)がないときはロードキャンセル

**Comment by tsuyoshicho** [comment]
nvcheck -r を明記

**Comment by tsuyoshicho** [comment]
Add lint
- [ ] https://github.com/hadolint/hadolint at docker

**Comment by tsuyoshicho** [comment]
stylelint format & fix action

**Comment by tsuyoshicho** [comment]
- vimlint (EVLxxx)
- black formatter

**Comment by tsuyoshicho** [comment]
Update Latest

see
https://github.com/mattn/efm-langserver/blob/bbab5580bef3821c3eeac4a8b5fb1c8b0bc8f942/langserver/handler.go

- Prefix
- Duration
- and other small point

and see
README python-pylint mapping
